# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.uit.com:
  peer1.uit.com:
  peer2.uit.com:
  peer0.ned.com:
  peer1.ned.com:
  peer2.ned.com:

networks:
  test:

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - test

  peer0.uit.com:


  
    container_name: peer0.uit.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.uit.com.com
      - CORE_PEER_ADDRESS=peer0.uit.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.uit.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.uit.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.uit.com:7051
      - CORE_PEER_LOCALMSPID=uitMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/uit.com/peers/peer0.uit.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/uit.com/peers/peer0.uit.com/tls:/etc/hyperledger/fabric/tls
        - peer0.uit.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - test
  peer1.uit.com:
    container_name: peer1.uit.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.uit.com
      - CORE_PEER_ADDRESS=peer1.uit.com:7053
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7053
      - CORE_PEER_CHAINCODEADDRESS=peer1.uit.com:7054
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7054
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.uit.com:7053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.uit.com:7053
      - CORE_PEER_LOCALMSPID=uitMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/uit.com/peers/peer1.uit.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/uit.com/peers/peer1.uit.com/tls:/etc/hyperledger/fabric/tls
        - peer1.uit.com/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7053:7053
    networks:
      - test
  peer2.uit.com:
    container_name: peer2.uit.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer2.uit.com
      - CORE_PEER_ADDRESS=peer2.uit.com:7055
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7055
      - CORE_PEER_CHAINCODEADDRESS=peer2.uit.com:7056
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7056
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.uit.com:7055
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.uit.com:7055
      - CORE_PEER_LOCALMSPID=uitMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/uit.com/peers/peer2.uit.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/uit.com/peers/peer2.uit.com/tls:/etc/hyperledger/fabric/tls
        - peer2.uit.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7055:7055
    networks:
      - test
  peer0.ned.com:
    container_name: peer0.ned.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.ned.com
      - CORE_PEER_ADDRESS=peer0.ned.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ned.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ned.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ned.com:9051
      - CORE_PEER_LOCALMSPID=NedMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/ned.com/peers/peer0.ned.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/ned.com/peers/peer0.ned.com/tls:/etc/hyperledger/fabric/tls
        - peer0.ned.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
    networks:
      - test
  peer1.ned.com:
    container_name: peer1.ned.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.ned.com
      - CORE_PEER_ADDRESS=peer1.ned.com:9053
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9053
      - CORE_PEER_CHAINCODEADDRESS=peer1.ned.com:9054
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9054
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.ned.com:9053
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.ned.com:9053
      - CORE_PEER_LOCALMSPID=NedMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/ned.com/peers/peer1.ned.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/ned.com/peers/peer1.ned.com/tls:/etc/hyperledger/fabric/tls
        - peer1.ned.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9053:9053
    networks:
      - test
  peer2.ned.com: 
    container_name: peer2.ned.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer2.ned.com
      - CORE_PEER_ADDRESS=peer2.ned.com:9055
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9055
      - CORE_PEER_CHAINCODEADDRESS=peer2.ned.com:9056
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9056
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.ned.com:9055
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.ned.com:9055
      - CORE_PEER_LOCALMSPID=NedMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/ned.com/peers/peer2.ned.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/ned.com/peers/peer2.ned.com/tls:/etc/hyperledger/fabric/tls
        - peer2.ned.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9055:9055
    networks:
      - test
